# SemanticBKIOctoMap config

# Octree parameter
block_depth: 2 # KITTIBAG: 3   Stanford: 2  SemanticKITTI: 2

# Kernel parameters
sf2:  1.0  # Actually sigma_0 in sparse kernel  10.0，决定了扩展块的影响程度，也不影响速度之类的   
ell: 1.0 # Length scale of the sparse kernel 0.3  0.4 for lidar   学长的可以小一点，smentickitti因为比较准，可以大一点，应该和地图分别率有关

# BGK Inference class prior pseudocounts
prior: 0.001 # each class

# Threshold on variance to distinguish known/unknown
var_thresh: 0.09

# Free/Occupied Thresholds
free_thresh: 0.3
occupied_thresh: 0.7
